CREATE DATABASE Online_shopping;
USE Online_shopping;

-- PRODUCTS TABLE
CREATE TABLE Products(
ProductID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Price DECIMAL(10,2) NOT NULL,
Stock INT DEFAULT 0,
Category VARCHAR(100)
);

-- CUSTOMERS TABLE
CREATE TABLE Customers(
CustomerID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Email VARCHAR(255),
Phone VARCHAR(15)
);

-- ORDERS TABLE
CREATE TABLE Orders(
OrderID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT,
OrderDate DATE DEFAULT(CURRENT_DATE),
TotalAmount DECIMAL(10,2),
FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
);

-- ORDER DETAILS TABLE
CREATE TABLE OrderDetails(
OrderDetailID INT AUTO_INCREMENT PRIMARY KEY,
OrderID INT,
ProductID INT,
Quantity INT, 
FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
FOREIGN KEY(ProductID) REFERENCES Products(ProductID));
